# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop --auto-correct --parallel
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - "5433:5432"
        env:
          POSTGRES_DB: testing_db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5433/testing_db_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          bundler-cache: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@master
        with:
          chromedriver_version: 'latest'
      - name: Set execute permissions for bin/rails
        run: chmod +x bin/rails
      - name: Setup test database
        run: bin/rails db:setup
      - name: Run tests
        run: bundle exec rspec
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/

